<?php namespace ProcessWire;

/**
 * ProcessWire Module AdminHidePageTreeByRole
 *
 * @author kixe Christoph Thelen
 * @license Licensed under GNU/GPL v3
 * inspired by AdminRestrictPageTree by Wanze, Kongondo and Netcarver
 *
 * For ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2.
 * http://www.processwire.com
 * 
 * @version 1.1.2
 * 
 * @since 1.0.1
 *      - added permission to reverse restriction set by this module
 *      - minor changes to prevent endless redirects, limitation of selectable redirect pages
 * @since 1.0.2
 *      - restrict view access for /page/*
 *      - added hook method noPermission()
 * @since 1.0.3
 *      - corrected typo in translation function
 * @since 1.0.4
 *      - landingPage per restrictedRole  myrole:1234 // pageID
 *      - strictly disallow /page/, /module/, /setup/, /access/ and all pages deriving from
 *      - allow only adminroot, /login/, /profile/ and custom pages under adminroot
 * @since 1.0.5
 *      - bugfix remove restriction for specified branches (add/edit) according to the Process instead of page IDs
 * @since 1.0.6
 *      - bugfix ProcessPageAdd check $input->get->parent_id AND $input->post->parent_id as well
 * @since 1.0.7
 *      - bugfix landingPage settings - trim page id before applying to selector
 * @since 1.0.8
 *      - changed on single restrictedRole to array of $restrictedRoles
 * @since 1.0.9
 *      - bugfix: hookPageViewable() let ProcessWire check access of the page beeing edited
 * @since 1.1.0
 *      - added hook ProcessLogin::afterLoginOutput to provide a logout button
 * @since 1.1.1 
 *      - added option to pull body content of home from other page, set in module settings
 * @since 1.1.2 
 *      - fixed bug handling of action link button clicks (ajax requests) called from ProcessPageLister 2023-06-27
 */

class AdminHidePageTreeByRole extends Process implements Module, ConfigurableModule {

    public static function getModuleInfo() {
		return array(
			'title'    => 'Admin Hide Page Tree by Role',
			'summary'  => 'Hides the page tree from users who have certain role(s).',
			'author'   => 'kixe',
			'version'  => 112,
			'href'     => 'https://processwire.com/talk/topic/6142-hide-page-tree-in-the-admin/#entry60087',
			'singular' => true,
			'autoload' => true,
            'permissions' => array(
                'admin-hide-page-tree-reverse' => __('Reverse the page tree view restriction for users assigned to another, excluded role. (AdminHidePageTreeByRole).'),
            )
		);
	}

    protected $landingPage = 2;

    protected $restrictedUserRoles = array(); 

    protected $editableBranches = array();

    static public function getDefaultData() {
        return array(
            'restrictedRoles' => array(),
            'landingPages' => null,
            'editablePages' => null,
            'adminPageBody' => null
        );
    }

    public function __construct() {
        foreach (self::getDefaultData() as $k => $v) {
            $this->$k = $v;
        }
    }

    public function init() {

        $this->addHookAfter('ProcessLogin::afterLoginOutput', $this, 'hookAfterLoginOutput');

        foreach ($this->restrictedRoles as $r) {
            if ($this->wire('user')->id && $this->wire('user')->hasRole($r)) $this->restrictedUserRoles[] = $r;
        }
        if (empty($this->restrictedUserRoles)) return;
        $this->editableBranches = $this->setEditableBranches($this->restrictedUserRoles);

        $landingPagesArray = array();
        if ($this->landingPages) {
            $landingPages = explode("\n", $this->landingPages);
            foreach ($landingPages as $line) {
                list($key,$value) = array_pad(explode(":", $line), 2, null);
                if($value) {
                    if (!$this->wire('pages')->get(trim($value))->viewable()) continue;
                    $landingPagesArray[trim($key)] = trim($value);
                }
            }
        }
        // If a user has multiple restricted roles and therefore multiple landing pages assigned, we take the first match
        foreach ($this->restrictedUserRoles as $restrictedRole) {
            if (!isset($landingPagesArray[$restrictedRole])) continue;
            $this->landingPage = $landingPagesArray[$restrictedRole];
            break;
        }

        if ($this->wire('user')->isLoggedin() && !$this->wire('user')->hasPermission('admin-hide-page-tree-reverse')) {
            $this->addHookBefore('ProcessHome::execute', $this, 'hookBeforeProcessHome');
            $this->addHookAfter('Page::viewable', $this, 'hookPageViewable');
        }
    }

    /**
     * BeforeHook in ProcessHome::execute()
     * Show welcome message (body field)
     * replace headline and body content from other page if set in module settings
     * render default message if body is not set
     * @param $event object HookEvent
     *
     */
    protected function hookBeforeProcessHome(HookEvent $event) {
        $event->replace = true;
        $page = $this->adminPageBody? wire('pages')->get($this->adminPageBody) : $event->object->getProcessPage();
        wire('page')->set('body', null);
        if ($page->body) {
            $page->of(true);
            $event->return = $page->body;
            if ($page->title) {
                $event->object->headline($page->title);
                $event->object->browserTitle($page->title);
            }
        } else {
            $event->return = wire('input')->wb? "<h2>".sprintf($this->_('Hi %s, welcome back!'), $this->getUserLabel($this->wire('user')))."</h2>" : // new line to make translatable
            "<p>".$this->_("You are logged in. Use the main menu to navigate.")."<p>";
        }
    }

    /**
     * get user label if different from name
     * @uses AdminThemeUikit
     * @param $user object User
     * @return string
     *
     */
    public function getUserLabel(User $user) {
        if (!$this->wire('modules')->isInstalled('AdminThemeUikit') || !$this->wire('user')->admin_theme == 'AdminThemeUikit') return $user->name;
        $userLabel = $this->wire('modules')->get('AdminThemeUikit')->userLabel;
        $userLabel = wirePopulateStringTags($userLabel, $user);
        return $userLabel;
    }

    /**
     * AfterHook in ProcessLogin::afterLoginOutput() which renders the output that appears
     * if there is nowhere to redirect to after login.
     * 
     * We add a Logout button for cases like this from here.
     * @param $event object HookEvent
     *
     */
    public function hookAfterLoginOutput(HookEvent $event) {
        $btn = $this->wire('modules')->get('InputfieldButton');
        $btn->value = $this->_('Logout');
        $btn->href = $this->config->urls->admin . 'login/logout/';
        $event->return .= "<p>" . $btn->render() . "</p>";
    }

    /**
     * AfterHook in Page::viewable()
     * max allowed: /admin/profile/ and other custom trees under /admin/
     * @param $event object HookEvent
     */
    protected function hookPageViewable(HookEvent $event) {

        // process page search ('page-edit' permission)
        // if ($event->object->id == 300) return;

        // prevent endless redirects
        if (wire('input')->get->login) {

            // Welcome back!
            $welcomeBack = $this->landingPage == 2? '?wb=1' : null;
            $url = $this->wire('pages')->get($this->landingPage)->url.$welcomeBack;
            // $this->wire('session')->redirect($url.$welcomeBack);
            // throws exception header already sent if sessionHistory is enabled
            // wire('config')->sessionHistory = 0;
            header("HTTP/1.1 301 Moved Permanently");
            header("Location: $url");
            exit(0);
        }

        // allow to handle action link button clicks (ajax requests) called from ProcessPageLister
        // validation of token is handled in ProcessPageList::ajaxAction()
        if ($event->object->process == 'ProcessPageList' &&
            $event->object->id == 3 &&
            wire('config')->ajax &&
            wire('input')->post->action &&
            wire('input')->post->ProcessPageLister) {
                return; 
        }

        // disallow pages 3=/page/, 21=/module/, 22=/setup/, 28=/access/
        if (in_array($event->object->id, array(3, 21, 22, 28))) {
            $event->return = false;
            return;
        }

        // let ProcessWire check access of the page beeing edited
        if (wire('input')->get->id == $event->object->id) return;

        // disallow pages having no process assigned
        if (empty($event->object->process)) {
            // $event->return = false;
            return;
        }


        // allow edit for pages living under a specified tree, allow page add under a specified parent
        // excepted from restriction by role ($this->editablePage
        // template or field based edit/add permission required
        $allowedProcesses = array('ProcessPageAdd', 'ProcessPageEdit', 'ProcessPageEditImageSelect', 'ProcessPageEditLink');
        if ($this->editablePages && in_array($event->object->process, $allowedProcesses)) {
            // ajax request e.g. repeater item
            if ($event->object->process == 'ProcessPageEdit' && wire('config')->ajax) return;
            if ($event->object->process == 'ProcessPageAdd') $id = isset(wire('input')->get->parent_id)? (int) wire('input')->get->parent_id : (int) wire('input')->post->parent_id;
            else $id = (int) wire('input')->get->id;
            if ($this->isEditableBranch($id, true)) return;
            $event->return = false;
        }

        // disallow trees 3=/page/, 21=/module/, 22=/setup/, 28=/access/
        $parentIDs = array(3, 21, 22, 28);
        foreach ($parentIDs as $parentID) {
            if ($event->object->parents->has(wire('pages')->get($parentID))) {
                $event->return = false;
                break;
            }
        }
        return;
    }

    /**
     * check if the branch is allowed for edits or adds?
     *
     * @param id page (edit)/ parent id (add)
     * @param addPageToParentsArray bool
     * @return bool
     *
     */
    protected function isEditableBranch($id, $addPageToParentsArray = false) {
        // quick exit
        // if (!$this->wire('pages')->get($id)->editable()) return false; // DO WE NEED THIS ???
        if (empty($this->editableBranches)) return false;
        // get family tree of the page to check
        $parentsArray = $this->wire('pages')->get($id)->parents->each('id');
        // add page itself
        if ($addPageToParentsArray) $parentsArray[] = $id;
        foreach ($this->editableBranches as $allowedParentID) {
            if (in_array($allowedParentID, $parentsArray)) return true;
         }
        return false;
    }

    /**
     * create array of page IDs of editable/ addable branches (parent ids) assigned to a specific role
     *
     * @param $roles array of role ids
     * @return array
     * @todo hookable? does not work! why? (:autoload module)
     */
    protected function ___setEditableBranches($roles) {
        if (!$this->editablePages) return array();
        $editableBranches = array();
        $editablePagesArray = explode("\n", $this->editablePages);
        if (empty($editablePagesArray)) return array();
        foreach ($editablePagesArray as $line) {
            list($key,$value) = array_pad(explode(":", $line), 2, null);
            if (!in_array($key, $roles) || $value === null) continue;
            $value = explode(",", $value);
            if (empty($value)) continue;
            foreach ($value as $pageID) {
                $pageID = (int) trim($pageID);
                $editableBranches[] = $pageID;
            }
        }
        return $editableBranches;   
    }

    public static function getModuleConfigInputfields(array $data) {
        $data = array_merge(self::getDefaultData(), $data);
		$fields = new InputfieldWrapper();
		$modules = wire('modules');

        $role_list = self::makeOptions(wire('roles'));
		$f = $modules->get("InputfieldAsmSelect");
		$f->name = "restrictedRoles";
		$f->label =  __("Roles that will have the pages tree, SETUP, MODULES and ACCESS area hidden from them.");
        $f->notes = __("Access allowed to custom admin pages and PROFILE if permission is granted. You may want to revoke restriction using process /page/edit/ and /page/add/ for pages and trees as specified below.");
        $f->options = $role_list;
        $f->value = $data['restrictedRoles'];
		$fields->add($f);

		$f = $modules->get("InputfieldTextarea");
		$f->name = "landingPages";
		$f->label =  __("Page to redirect restricted users after login");
        $f->description =  __("Assign a page ID to role in the format 'role-name: pageID'. One per line if multiple.");
        $f->notes = __("No redirect if user is not permitted to view assigned page. If a user has multiple restricted roles and therefore multiple landing pages assigned, we take the first match. Default landing page is admin root (id=2)");
        $f->value = $data['landingPages'];
        $fields->add($f);

        $f = $modules->get("InputfieldTextarea");
        $f->name = "editablePages";
        $f->label =  __("Allow Page Edit and Add by Branch");
        $f->description =  __("Assign parent IDs to role in the format 'role-name: pageID-1, pageID-2, ...'. One per line if multiple. Removes add/edit restriction for pages under the specified branch.");
        $f->notes = __("Mainly to allow page edit via modal via page reference fields");
        $f->value = $data['editablePages'];
        $fields->add($f);

        $page_list = self::makeOptions(wire('pages')->find("body!='',include=all"), 'url');
        $f = $modules->get("InputfieldSelect");
        $f->name = "adminPageBody";
        $f->label =  __("Page from which 'home' content should be retrieved");
        $f->description =  __("If a user is not permitted to see the page tree, a welcome message is displayed by default on the admin home page (id=2). You may want to select a page to drag alternative content out of the body field that is rendered instead.");
        $f->options = $page_list;
        $f->value = $data['adminPageBody'];
        $fields->add($f);

        return $fields;
	}

    public static function makeOptions($wireArray, $property = 'title|name') {
        $options = array();
        foreach ($wireArray as $f) {
            $label = $f->get($property);
            $key  = $f->name;
            $options[$key] = $label;
        }
        return $options;
    }
}
